import assert from 'node:assert/strict';
import test from 'node:test';

import {
  assessTwoWitnessHandoff,
  generateP256KeyPair,
  sealCrossingEnvelope,
  sealReceipt,
} from '../src/index.ts';

const THING_REF = 'sha256:' + '2'.repeat(64);

async function sourceCrossing(
  keys: Awaited<ReturnType<typeof generateP256KeyPair>>,
  overrides: Record<string, any> = {},
) {
  return sealCrossingEnvelope({
    schema: 'relatte.crossing-envelope/v0',
    protocol_version: '0',
    source_particular: 'particular:father',
    source_world: 'world:father',
    source_history_head: null,
    parents: [],
    declared_kind: 'TWO_WITNESS_HANDOFF',
    payload_refs: [{
      address: THING_REF,
      role: 'payload',
      media_type: 'application/octet-stream',
    }],
    requested_effect: {
      kind: 'handoff-candidate',
      authority: 'receiver-local',
    },
    capability_ref: null,
    privacy_policy: null,
    audience_policy: null,
    return_address: 'relatte:return:father',
    created_at: '2026-10-07T16:00:00.000Z',
    signing: null,
    extensions: {
      two_witness_handoff: {
        schema: 'relatte.two-witness-handoff/v0',
        handoff_id: 'handoff:001',
        receiver_world: 'world:child',
        receiver_particular: 'particular:child',
        thing_ref: THING_REF,
      },
    },
    ...overrides,
  }, keys);
}

async function receiverWitness(
  crossing: Record<string, any>,
  keys: Awaited<ReturnType<typeof generateP256KeyPair>>,
  overrides: Record<string, any> = {},
) {
  const binding = crossing.extensions.two_witness_handoff;
  const draft = {
    schema: 'relatte.receipt/v0',
    crossing_id: crossing.crossing_id,
    world_id: binding.receiver_world,
    receiver_particular: binding.receiver_particular,
    kind: 'RECEIVED',
    semantic_effect: 'none',
    contract_ref: null,
    pre_state_ref: null,
    post_state_ref: null,
    descendant_refs: [],
    residual_refs: [],
    note: 'Independent receiver-side witness of the handoff.',
    created_at: '2026-10-07T16:01:00.000Z',
    extensions: {
      two_witness_handoff: {
        schema: 'relatte.two-witness-handoff/v0',
        handoff_id: binding.handoff_id,
        source_particular: crossing.source_particular,
        receiver_world: binding.receiver_world,
        receiver_particular: binding.receiver_particular,
        thing_ref: binding.thing_ref,
      },
    },
    ...overrides,
  };
  return sealReceipt(draft, keys);
}

test('TWO-WITNESS-CRUCIBLE-001: one valid source witness remains only CLAIMED', async () => {
  const sourceKeys = await generateP256KeyPair();
  const crossing = await sourceCrossing(sourceKeys);

  const result = await assessTwoWitnessHandoff({ crossing });

  assert.equal(result.status, 'CLAIMED');
  assert.equal(result.independence_basis, 'NONE');
  assert.deepEqual(result.reasons, ['SOURCE_WITNESS_ONLY']);
});

test('TWO-WITNESS-CRUCIBLE-001: matching signed source and receiver witnesses corroborate the handoff', async () => {
  const sourceKeys = await generateP256KeyPair();
  const receiverKeys = await generateP256KeyPair();
  const crossing = await sourceCrossing(sourceKeys);
  const receipt = await receiverWitness(crossing, receiverKeys);

  const result = await assessTwoWitnessHandoff({
    crossing,
    receiver_receipt: receipt,
  });

  assert.equal(result.status, 'CORROBORATED');
  assert.equal(result.handoff_id, 'handoff:001');
  assert.equal(result.independence_basis, 'DISTINCT_SIGNING_KEYS_ONLY');
});

test('TWO-WITNESS-CRUCIBLE-001: same key wearing both hats is HOLD', async () => {
  const oneKey = await generateP256KeyPair();
  const crossing = await sourceCrossing(oneKey);
  const receipt = await receiverWitness(crossing, oneKey);

  const result = await assessTwoWitnessHandoff({
    crossing,
    receiver_receipt: receipt,
  });

  assert.equal(result.status, 'HOLD');
  assert.deepEqual(result.reasons, ['WITNESS_KEYS_NOT_DISTINCT']);
});

test('TWO-WITNESS-CRUCIBLE-001: distinct keys do not prove distinct custody', async () => {
  // Both keys are intentionally generated by this one process. The protocol can
  // prove key distinctness, but cannot prove distinct operators, machines,
  // custody domains, or humans from signatures alone.
  const sourceKeys = await generateP256KeyPair();
  const receiverKeys = await generateP256KeyPair();
  const crossing = await sourceCrossing(sourceKeys);
  const receipt = await receiverWitness(crossing, receiverKeys);

  const result = await assessTwoWitnessHandoff({
    crossing,
    receiver_receipt: receipt,
  });

  assert.equal(result.status, 'CORROBORATED');
  assert.equal(result.independence_basis, 'DISTINCT_SIGNING_KEYS_ONLY');
  assert.ok(result.laws.includes('DISTINCT KEYS != INDEPENDENT CUSTODY'));
});

test('TWO-WITNESS-CRUCIBLE-001: receiver disagreement on target particular is HOLD', async () => {
  const sourceKeys = await generateP256KeyPair();
  const receiverKeys = await generateP256KeyPair();
  const crossing = await sourceCrossing(sourceKeys);
  const receipt = await receiverWitness(crossing, receiverKeys, {
    receiver_particular: 'particular:not-the-child',
  });

  const result = await assessTwoWitnessHandoff({
    crossing,
    receiver_receipt: receipt,
  });

  assert.equal(result.status, 'HOLD');
  assert.ok(result.reasons.includes('RECEIVER_PARTICULAR_DISAGREEMENT'));
});

test('TWO-WITNESS-CRUCIBLE-001: signed disagreement about the handed thing is HOLD', async () => {
  const sourceKeys = await generateP256KeyPair();
  const receiverKeys = await generateP256KeyPair();
  const crossing = await sourceCrossing(sourceKeys);

  const wrongExtensions = structuredClone(crossing.extensions);
  wrongExtensions.two_witness_handoff.thing_ref =
    'sha256:' + '3'.repeat(64);

  const receipt = await receiverWitness(crossing, receiverKeys, {
    extensions: {
      two_witness_handoff: {
        schema: 'relatte.two-witness-handoff/v0',
        handoff_id: 'handoff:001',
        source_particular: crossing.source_particular,
        receiver_world: 'world:child',
        receiver_particular: 'particular:child',
        thing_ref: wrongExtensions.two_witness_handoff.thing_ref,
      },
    },
  });

  const result = await assessTwoWitnessHandoff({
    crossing,
    receiver_receipt: receipt,
  });

  assert.equal(result.status, 'HOLD');
  assert.ok(result.reasons.includes('HANDOFF_BINDING_DISAGREEMENT'));
});

test('TWO-WITNESS-CRUCIBLE-001: a valid receipt replayed against a different crossing is HOLD', async () => {
  const sourceKeysA = await generateP256KeyPair();
  const sourceKeysB = await generateP256KeyPair();
  const receiverKeys = await generateP256KeyPair();

  const crossingA = await sourceCrossing(sourceKeysA);
  const receiptA = await receiverWitness(crossingA, receiverKeys);

  const crossingB = await sourceCrossing(sourceKeysB, {
    source_particular: 'particular:other-father',
    created_at: '2026-10-07T16:02:00.000Z',
  });

  const result = await assessTwoWitnessHandoff({
    crossing: crossingB,
    receiver_receipt: receiptA,
  });

  assert.equal(result.status, 'HOLD');
  assert.ok(result.reasons.includes('CROSSING_ID_DISAGREEMENT'));
  assert.ok(result.reasons.includes('HANDOFF_BINDING_DISAGREEMENT'));
});

test('TWO-WITNESS-CRUCIBLE-001: receiver refusal does not constitute positive continuity', async () => {
  const sourceKeys = await generateP256KeyPair();
  const receiverKeys = await generateP256KeyPair();
  const crossing = await sourceCrossing(sourceKeys);
  const receipt = await receiverWitness(crossing, receiverKeys, {
    kind: 'REFUSED',
    semantic_effect: 'none',
  });

  const result = await assessTwoWitnessHandoff({
    crossing,
    receiver_receipt: receipt,
  });

  assert.equal(result.status, 'HOLD');
  assert.ok(result.reasons.includes('RECEIVER_DID_NOT_POSITIVELY_RECEIVE'));
});

test('TWO-WITNESS-CRUCIBLE-001: post-signature tampering invalidates the second witness', async () => {
  const sourceKeys = await generateP256KeyPair();
  const receiverKeys = await generateP256KeyPair();
  const crossing = await sourceCrossing(sourceKeys);
  const receipt = await receiverWitness(crossing, receiverKeys);

  const tampered = structuredClone(receipt);
  tampered.receiver_particular = 'particular:tampered-after-signing';

  const result = await assessTwoWitnessHandoff({
    crossing,
    receiver_receipt: tampered,
  });

  assert.equal(result.status, 'HOLD');
  assert.deepEqual(result.reasons, ['INVALID_RECEIVER_WITNESS']);
});

test('TWO-WITNESS-CRUCIBLE-001: source mutation after signing destroys even the first witness', async () => {
  const sourceKeys = await generateP256KeyPair();
  const crossing = await sourceCrossing(sourceKeys);

  const tampered = structuredClone(crossing);
  tampered.extensions.two_witness_handoff.receiver_particular =
    'particular:rewritten-child';

  const result = await assessTwoWitnessHandoff({ crossing: tampered });

  assert.equal(result.status, 'HOLD');
  assert.deepEqual(result.reasons, ['INVALID_SOURCE_WITNESS']);
});
